<a href="https://colab.research.google.com/github/AdityaKumbhar21/Natural_Language_Processing/blob/main/Word_Embedding_techniques_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
!pip install tensorflow

In [18]:
from tensorflow.keras.preprocessing.text import one_hot

In [19]:
# sentences

sentences = [  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

sentences

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [20]:
# defining the vocabulary_size
voc_size =10000

#one hot encoding
one_hot_r = [one_hot(words, voc_size) for words in sentences]
print(one_hot_r)

[[3983, 4887, 4594, 7059], [3983, 4887, 4594, 9458], [3983, 6530, 4594, 1632], [4603, 9347, 4645, 8246, 4996], [4603, 9347, 4645, 8246, 3288], [2246, 3983, 7369, 4594, 1536], [3195, 7532, 6875, 8246]]


In [21]:
## Word embedding rep
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [22]:
## adding padding
# defining max_len for sentence
max_len_sent = 8
embedded_docs = pad_sequences(one_hot_r, maxlen=max_len_sent, padding='pre') # padding -> pre and post add zeros at start or at end
print(embedded_docs)

[[   0    0    0    0 3983 4887 4594 7059]
 [   0    0    0    0 3983 4887 4594 9458]
 [   0    0    0    0 3983 6530 4594 1632]
 [   0    0    0 4603 9347 4645 8246 4996]
 [   0    0    0 4603 9347 4645 8246 3288]
 [   0    0    0 2246 3983 7369 4594 1536]
 [   0    0    0    0 3195 7532 6875 8246]]


In [28]:
## implementing embedding layer
dim = 10 # feature representation for each word in sentence
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=max_len_sent))
model.compile('adam','mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [25]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [29]:
embedded_docs[0]

array([   0,    0,    0,    0, 3983, 4887, 4594, 7059], dtype=int32)

In [30]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 296ms/step


array([[ 3.8960461e-02, -5.9780702e-03, -1.2835346e-02,  3.8526598e-02,
         2.0386461e-02,  4.3118510e-02, -4.8532199e-02, -4.2751897e-02,
        -2.6084770e-02,  4.9842987e-02],
       [ 3.8960461e-02, -5.9780702e-03, -1.2835346e-02,  3.8526598e-02,
         2.0386461e-02,  4.3118510e-02, -4.8532199e-02, -4.2751897e-02,
        -2.6084770e-02,  4.9842987e-02],
       [ 3.8960461e-02, -5.9780702e-03, -1.2835346e-02,  3.8526598e-02,
         2.0386461e-02,  4.3118510e-02, -4.8532199e-02, -4.2751897e-02,
        -2.6084770e-02,  4.9842987e-02],
       [ 3.8960461e-02, -5.9780702e-03, -1.2835346e-02,  3.8526598e-02,
         2.0386461e-02,  4.3118510e-02, -4.8532199e-02, -4.2751897e-02,
        -2.6084770e-02,  4.9842987e-02],
       [-4.9271610e-02, -1.0355227e-03, -2.6169514e-02,  4.7528017e-02,
         3.3974756e-02,  8.4377155e-03, -2.4401307e-02, -2.5616849e-02,
        -4.6859335e-02,  3.1016767e-05],
       [ 2.1340217e-02, -2.6870979e-02, -4.9575627e-02, -2.7847171e-02,
   